name: Vmob Deploy

on: 
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout range
      uses: actions/checkout@v2
      with:
        path: vlib/range
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Build example
      run: |
        v self
