name: Vmob Deploy

on: 
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout range
      uses: actions/checkout@v2
      with:
        path: vlib/range
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Build example
      run: |
        v vmob.v
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            LICENSE.txt
            *.zip
    

